#Android Config
platformName=Android
platformVersion=14
deviceName=POCO C51
udid=YPCM8LMFA6XGXWHY
appPackage=com.finjpartnerapp
appActivity=com.finjpartnerapp.MainActivity
automationName=UiAutomator2
noReset=true
fullReset=false
appPath=D:\\Builds\\FinjPartnerApp.apk
